### ISSUE TITLE
Rename the .net plugins for consistency

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#1045]
The original .net plugin was named `plugin-dot-net-core` so the others I added were named `plugin-dot-net-*`, but the ones I'm working on now are named `plugin-dotnet-paket` and `plugin-dotnet-scripting` which matches how .net is spelled out (e.g. the [GitHub org](https://github.com/dotnet) and [cli tools](https://docs.microsoft.com/en-us/dotnet/core/tools/)). I was going to rename the rest to match but wanted too see what others thought before doing it.

**Comment by stefanbuck** [comment]
This would be a great hacktober issue. I'll add the label.
