### ISSUE TITLE
Support the history API events

### ISSUE THREAD

**Issue by EnixCoda** [OctoLinker/OctoLinker#1119]
**Describe the feature**
Support events related to the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History), e.g. `pushstate` instead of `pjax:*`.

**Demo**
https://github.com/OctoLinker/injection/blob/0e34e2aeed1a2d80bf585eacc9734a7e96f217af/index.js#L12

Should listen to `pushstate`, `popstate`, etc.

**Additional information**
I'm the maintainer of another extension for GitHub, [Gitako](https://github.com/EnixCoda/Gitako). Some users found that OctoLinker does not work after redirecting with Gitako, which uses [PJAX-API](https://falsandtru.github.io/pjax-api/) internally. [See previous discussions](https://github.com/EnixCoda/Gitako/issues/97).

Instead of asking OctoLinker to support the PJAX event emitted from PJAX-API, which emits `pjax:ready` instead of `pjax:end` after redirecting. I'd suggest OctoLinker to listen to events like `pushstate`, so that maintainers of different extensions do not need to have unnecessary compromises for compatibilities between extensions (I was going to ask OctoLinker to listen to `pjax:ready` but found that it was a bad idea :P).

**Comment by stefanbuck** [comment]
Thanks for filling this issue. A while ago Octotree was having the same issue and they solved it by dispatching `pjax:start` and `pjax:end` events themselves see https://github.com/ovity/octotree/pull/861. I think this is a valid solution since GitHub itself is still using PJAX events.

**Comment by EnixCoda** [comment]
I see. Thank you!
