### ISSUE TITLE
Chrome GitHub pages crashing when OctoLinker enabled

### ISSUE THREAD

**Issue by with-heart** [OctoLinker/OctoLinker#1121]
**Describe the bug**
When loading certain GitHub pages in Chrome, OctoLinker causes the page to go unresponsive after partially loading. Page content is partially or fully rendered, but content cannot be interacted with (text selected, etc.) and switching to another tab and back displays a blank page.

**To Reproduce**
1. Disable all extensions
2. Visit https://github.com/framer/motion/issues/364 (the first page where I noticed this happening)
3. Page loads and is responsive
4. Enable only OctoLinker extension
5. Reload the page or open it in a new tab
6. Page never finishes loading

**Expected behavior**
The page should fully load in a timely manner while retaining expected interactivity.

**Additional context**

I noticed that when I load the page, two network requests are fired that resolve almost immediately:

![image](https://user-images.githubusercontent.com/1954752/99151736-20e27400-266b-11eb-990c-5498b97d2382.png)

After enabling OctoLinker, the two network requests occur but never leave the "Pending" status:

![image](https://user-images.githubusercontent.com/1954752/99151746-36579e00-266b-11eb-8e32-92690a544a46.png)

I allowed the tab to sit for ~15 minutes and the requests never completed. 

OctoLinker version: 6.6.0
Chrome version: Tested with 86.0.4240.193 and 86.0.4240.198
OS: macOS 10.15.5

**Comment by stefanbuck** [comment]
Thanks for letting us know. I guess one of the code snippets is causing this behavior. I'll investigate into this

**Comment by with-heart** [comment]
@stefanbuck Thank you! If there's anything more I can do to help debug, let me know.

**Comment by stefanbuck** [comment]
What a journey ... after digging through the entire lifecycle of OctoLinker I found the issues. The regular expression which we use to figure out whether or not a url is valid is causing this problem.  Urls like `https://github.comframer-motion-supported-elements/index.js` are causing this problem.  A [stackoverflow comment](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url/22648406#comment74496184_22648406) is mentioned this issue as well.

**Comment by stefanbuck** [comment]
This RegExp seems to work https://stackoverflow.com/a/3809435/2121324

**Comment by stefanbuck** [comment]
PR is in place. I'm going to release a new version early next week.

**Comment by with-heart** [comment]
Thank you so much @stefanbuck! 🙏

**Comment by stefanbuck** [comment]
No worries, thanks for reporting the issue
