### ISSUE TITLE
Safari: Token can't be removed

### ISSUE THREAD

**Issue by fregante** [OctoLinker/OctoLinker#1170]
**Describe the bug**

If you try to empty the token field, it's not saved as "empty"

**To Reproduce**
1. Go to the options page
2. Empty the previously-saved token field
3. Refresh the page
4. The old token is still there

**Expected behavior**

If I remove the token, it should be removed from storage

**Additional context**

Gif showing deletion + refresh (twice, in Safari but I assume it's the same everywhere)

![gif](https://user-images.githubusercontent.com/1402241/103511570-ee642480-4e2c-11eb-95c1-2c8f142ad899.gif)

**Comment by stefanbuck** [comment]
I just checked Chrome and Firefox and both are removing the token as expected. Maybe Safari struggles with setting the value to `null`. I'll look into this once I start working on #1167  https://github.com/OctoLinker/OctoLinker/blob/98c74a5b2c6cf4bc52561df737ba4b7ad870fd9b/packages/helper-settings/SettingsForm.js#L49

**Comment by fregante** [comment]
You're right. Safari’s storage implementation is non-standard. I don't know what I expected.

```
await browser.storage.local.get('a')
> (returns the whole storage anyway)
```

However in Refined GitHub apparently the polyfill is still being applied so the API works correctly in every browser: native in Firefox, polyfilled in Chrome and Safari.

**Comment by fregante** [comment]
By the way, Refined GitHub is about to add some scope-checking mechanism/UI. Maybe you have some comments before we merge it or if you'd like to bring some logic/UI over to OctoLinker.

**Comment by stefanbuck** [comment]
> However in Refined GitHub apparently `webextensions-polyfill` is still being applied so the API works correctly in every browser: native in Firefox, polyfilled in Chrome and Safari.

We're using `webextension-polyfill` already 😕 However, setting the value to an empty string solves the issue.

**Comment by stefanbuck** [comment]
> By the way, Refined GitHub is about to add some scope-checking mechanism/UI. Maybe you have some comments before we merge it or if you'd like to bring some logic/UI over to OctoLinker.

This looks really neat and I might steal it at some point 😉  Thanks for sharing
