### ISSUE TITLE
Linking with aliased directories

### ISSUE THREAD

**Issue by Milo123459** [OctoLinker/OctoLinker#1236]
[Go here](https://github.com/vercel/hyper-site/blob/main/pages/index.js) and click the components/terminal. It should see if the directory exists and if it does take you there.

**Comment by fregante** [comment]
Where does the aliasing happen? `import 'components/page'` is normally resolved to `$root/node_modules/components/page`. Something along the way is aliasing `components` to `$root/components`, but I can't find it.
