### ISSUE TITLE
Firefox extension is not automatically published

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#128]
https://github.com/OctoLinker/browser-extension/pull/119 added automatic publishing to the Chrome extension store, but we don't yet have the same for Firefox. Something like https://github.com/kewisch/pyamo might be able to help with this.

EDIT: I also found https://www.npmjs.com/package/firefox-extension-deploy

**Comment by prometh07** [comment]
Maybe https://github.com/mozilla/web-ext ?

**Comment by bfred-it** [comment]
web-ext can build, lint, run and sign, but not deploy for now: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference

**Comment by josephfrazier** [comment]
It looks like @bfred-it ^ has found a way to do this with `web-ext`: https://github.com/mozilla/web-ext/issues/804#issuecomment-302588357
