### ISSUE TITLE
github action run link support

### ISSUE THREAD

**Issue by staabm** [OctoLinker/OctoLinker#1298]
### Expected Behavior

would be great to get an status-indication on a github action run link, e.g. `https://github.com/redaxo/redaxo/runs/2604529031`

something like red/yellow/green would already be usefull (errored, succeded, pending).

we use this links pretty often in the automation, so we can easily lookup the status of a action job.
to have a status idication even before following such a link would be a real timesaver

### What actually happened?

this links seem to be not yet supported

**Comment by xt0rted** [comment]
This sounds like it'd be better suited for [fregante/github-issue-link-status](https://github.com/fregante/github-issue-link-status) or maybe a fork of that extension.

**Comment by stefanbuck** [comment]
I agree with @xt0rted. OctoLinker main focus should remain code navigation. Another extension you might want to flag this idea is [sindresorhus/refined-github]( https://github.com/sindresorhus/refined-github).
