### ISSUE TITLE
Feature Request template broken

### ISSUE THREAD

**Issue by mal-tee** [OctoLinker/OctoLinker#1406]
Seems like the template for feature requests is broken, I can't select it in the "new issue"-form. If I it [view it in GitHub](https://github.com/OctoLinker/OctoLinker/blob/486b00d752375657327980becff2d8a3d0ac553a/.github/ISSUE_TEMPLATE/feature_request.yml), this error occurs:

```
There is a problem with this template

issue_body is not a permitted key. Learn more. 
```

**Comment by stefanbuck** [comment]
Thanks for the hint. Looks like this key is deprecated since a couple months already.
