### ISSUE TITLE
cant understand ... js/ts config.json ... Absolute Imports and Module path aliases

### ISSUE THREAD

**Issue by withrvr** [OctoLinker/OctoLinker#1425]
### Describe the feature

```

can't understand
jsconfig.json  tsconfig.json
Absolute Imports and Module path aliases

```

### Demo

![image](https://user-images.githubusercontent.com/69628500/147603479-3d8bf393-68b9-4ab3-9805-2290fce17036.png)

![image](https://user-images.githubusercontent.com/69628500/147603538-704fcb39-832e-4fbf-8c7d-ab4ff887999f.png)

**Comment by stefanbuck** [comment]
Duplicate, but I hear you. Would love to see this feature myself. Maybe I find time for this in 2022 or someone want's to pair on this https://github.com/OctoLinker/OctoLinker/issues/492
