### ISSUE TITLE
links not working for - Absolute Imports and Module path aliases - ( javascript / typescript )

### ISSUE THREAD

**Issue by withrvr** [OctoLinker/OctoLinker#1426]
### Expected Behavior

```
the link should be shown
for import statements

which is been used by many uses ( devs )
because make easy and fast ..... will working on projects

and then also ... it is not working as links
```

### What actually happened?

```
i have configred this
```

![image](https://user-images.githubusercontent.com/69628500/147604286-230d2ff1-d597-4c00-9a9e-b21a9908a94d.png)

```
but it was not working as links ...
```

![image](https://user-images.githubusercontent.com/69628500/147604288-3ae84fdf-f45e-4a2e-905c-8fea03e1f265.png)

### URL

https://github.com/withrvr/Boilerplate-Nextjs/blob/3e8f8bb/pages/_app.tsx

### Anything else we should know?

```
it is called as 

Absolute Imports and Module path aliases

which is configured in using

jsconfig.json ( in javascript )
tsconfig.json ( in typescript )
```

**Comment by stefanbuck** [comment]
Similar to https://github.com/OctoLinker/OctoLinker/issues/1425#issuecomment-1002299781
