### ISSUE TITLE
This app is currently not available in your country or region.

### ISSUE THREAD

**Issue by AjayShanker-geek** [OctoLinker/OctoLinker#1428]
### Expected Behavior

Expected to install it on the App Store

### What actually happened?

**App Not Available**
This app is currently not available in your country or region.

### Anything else we should know?
My country is Singapore🇸🇬

_No response_

**Comment by stefanbuck** [comment]
Thanks for opening this issue. The extension listing is disabled for everyone due to a pending state in the app store. I don't have any visibility since the safari version is handled by @fregante but he is aware of this problem and should be resolved soon. Sorry for the confusion

**Comment by fregante** [comment]
My bad! I had let my Apple Developer Account (the €99) expire. It should be to go good now, maybe it will take a bit to show up again. Maybe leave this open until it does. 

![image](https://user-images.githubusercontent.com/1402241/147842257-12b4b54a-67e4-4b01-a7ed-507c12b10a1c.jpeg)
