### ISSUE TITLE
Add dependencies list/report

### ISSUE THREAD

**Issue by TravisCarden** [OctoLinker/OctoLinker#1520]
### Describe the feature

I would love to see OctoLinker add a list or report of project dependencies to the `README` (or in a new tab or something) like [Package Hub](https://chrome.google.com/webstore/detail/package-hub/hnnjnbmjanpeoeapjllonejjgoonilal) used to. (It doesn't seem to work anymore.) Example screenshots from that extension:

<br />

![npm](https://user-images.githubusercontent.com/959246/158193312-0e67304d-2ba5-481f-8200-b09ff34e9946.jpeg) ![composer](https://user-images.githubusercontent.com/959246/158193391-448f87ad-9ae6-4741-a2ab-ee45387e93d5.jpeg)

### Demo

https://chrome.google.com/webstore/detail/package-hub/hnnjnbmjanpeoeapjllonejjgoonilal

**Comment by stefanbuck** [comment]
I think you're looking for https://github.com/npmhub/npmhub 😉

**Comment by TravisCarden** [comment]
Thanks, @stefanbuck. Unfortunately, npmhub doesn't support Composer, but I appreciate the recommendation.

p.s. - While we're "talking", thanks for this excellent extension! 🙂

**Comment by stefanbuck** [comment]
Ahh I see. I think such a feature is out of scope of this project. I found the repo and maybe you're fancy forking and fixing it https://github.com/BrainMaestro/packagehub

**Comment by TravisCarden** [comment]
> maybe you're fancy

Lol

Fair enough. Thanks! 🙂
