### ISSUE TITLE
Not highlighting code URL (tsconfig paths aliases)

### ISSUE THREAD

**Issue by Bellisario** [OctoLinker/OctoLinker#1592]
### Expected Behavior

OctoLinker needed to highlight the imported file, also if using a tsconfig alias.

### What actually happened?

No highlight was provided.

### URL

https://github.com/PuruVJ/macos-web/blob/5f8af1e675dd559d200425e05706260ea4a7d736/src/components/Desktop/Desktop.svelte

### Anything else we should know?

The URL provided contains an emoji, I don't know if this is the problem, but instead I think the problem is that the emoji is just an alias in tsconfig.

P.S.: I don't know if this is a bug or a feature request for you, but I opened a bug because I was expecting it works also with import aliases (or emojis???).

**Comment by stefanbuck** [comment]
Yep that would be feature request. It has been requested in the past https://github.com/OctoLinker/OctoLinker/issues/492 but I never found time to look into this further given it's relatively complex.
