### ISSUE TITLE
Stopped working after opening another page

### ISSUE THREAD

**Issue by kidonng** [OctoLinker/OctoLinker#1604]
### Expected Behavior

Open https://github.com/OctoLinker/OctoLinker, then click `package.json`, the packages should be linked.

### What actually happened?

The packages aren't linked until you refresh the page.

### Anything else we should know?

This is presumably broken by GitHub's recent switch from PJAX to Turbo. Strangely I could not find PJAX related code in OctoLinker, will attempt to investigate later if I got the time.

**Comment by stefanbuck** [comment]
Thanks for the nudge. @fregante raised a PR on the related dependency a few days ago https://github.com/OctoLinker/injection/pull/21. I'll look into tomorrow

**Comment by stefanbuck** [comment]
This issue has been fix in the latest version 6.10.4. it is available for chrome already, Firefox and Safari will follow soon

**Comment by stefanbuck** [comment]
@fregante do you mind uploading a new version for Safari, whenever you have time for it. Thank you

**Comment by fregante** [comment]
<img width="469" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/179734465-7dc33f53-4157-4d12-a745-20fe4fb1c74b.png">
