### ISSUE TITLE
Will you be porting the extension to Edge browser?

### ISSUE THREAD

**Issue by Spudley** [OctoLinker/OctoLinker#179]
Hi.

Microsoft's Edge browser now supports extensions with a very similar structure to Chrome's.

Will you be porting your extension to Edge?

**Comment by stefanbuck** [comment]
Supporting another browser isn't in our scope right now. However, we would accept a PR that implements Edge support.

https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/

**Comment by stefanbuck** [comment]
It's there https://twitter.com/OctoLinker/status/1216842357540130816
