### ISSUE TITLE
Bad links in Rust commit comment

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#284]
**Browser name:** Chrome

**Browser version:** Version 56.0.2924.87 (64-bit)

**OctoLinker version:** git master (cc1bae8b95d60d14c058ce1e610e84619395bfeb)

**URL and line number where issue occurs:** https://github.com/brson/annotated-std-rs/commit/e50c2b16455ceff29488bf1f058b6c10906ef990#commitcomment-12409226

**Expected behavior:** no links in commit comment

**Actual behavior:** both `it` and `Apache` are incorrectly linkified:

<img width="695" alt="screen shot 2017-02-15 at 10 28 26 pm" src="https://cloud.githubusercontent.com/assets/6473925/23006145/2429de7e-f3ce-11e6-8eda-c9539e98b6e2.png">

---

There's also some linkified comments (within the code, not commit comments) further down in the file, for example https://github.com/brson/annotated-std-rs/commit/e50c2b16455ceff29488bf1f058b6c10906ef990#diff-e69647f2cc8f2ccdbff28d2fbb925a1fR17. We might be might able to fix this with something similar to https://github.com/OctoLinker/browser-extension/commit/2c347a452a50f713a88863e6dcff869682c4594c

**Comment by stefanbuck** [comment]
Seems to be not an issue anymore with the latest version 😃
