### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by tjmehta** [OctoLinker/OctoLinker#29]
I love this plugin. I would love to see safari support. Thanks!

**Comment by tjmehta** [comment]
Octotree, another browser plugin I love has recently started supported all browsers. It looks like a good examples of how to support multiple plugin formats ( Firefox too #24). Check out the source here: https://github.com/buunguyen/octotree

**Comment by stefanbuck** [comment]
The problem is not to build these extensions, but keep them up to date with the registries. Accutlay once per week I run a script which generates the cache list for the npm, bower and comperser registry. 

I'm planning to move the core from a cache list to a live resolver solution, but I need time to develop it. Soon as this is done I can start thinking about a safari and firefox version :wink:

**Comment by tjmehta** [comment]
Ah, I was wondering what you were doing the linking. Is it not possible to do everything clientside (maybe parse npmjs or bower websites for the github links - or maybe reverse engineer their apis)?

**Comment by stefanbuck** [comment]
Yeah, that's the plan. I will start working on it soon :wink:

**Comment by JaKXz** [comment]
Any updates on the safari extension? The developer preview for Safari 10 is actually pretty good, IMO :)

**Comment by stefanbuck** [comment]
Nope, unfortanly not. Do you know if Safari 10 supports the [WebExtension API](https://wiki.mozilla.org/WebExtensions)?

**Comment by josephfrazier** [comment]
I looked into this for a little bit, and found that while Safari doesn't support the WebExtension API, it might not be very difficult to shim it out, using something like https://github.com/kritollm/chrome-extension-api-for-safari-and-firefox

Another potential option could be to build a userscript version of the extension, so Safari users could install it using [Tampermonkey](https://tampermonkey.net/?browser=safari), etc

**Comment by nikitavoloboev** [comment]
I too would love for Safari to be supported

**Comment by sindresorhus** [comment]
Safari will soon support the WebExtensions API: 
- https://hacks.mozilla.org/2020/06/welcoming-safari-to-the-webextensions-community/
- https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by stefanbuck** [comment]
Thanks for the update. Do you know if a developer account is required to submit web extensions? The developer program is super pricey to distribute a single free item.

**Comment by nesl247** [comment]
Yes, it is still required. Though if you already have one for any purpose, you could use that.

I'd be willing to chip in to help pay for it.

**Comment by fregante** [comment]
Follow https://github.com/sindresorhus/refined-github/issues/14 and https://github.com/sindresorhus/refined-github/pull/3677 for more details.

Supporting Safari is not particularly difficult, but we still need help with auto-deployment to the App Store.

**Comment by fregante** [comment]
I can publish OctoLinker under my (SindreSorhus-sponsored) account if you want. I'm already publishing [npmhub](https://apps.apple.com/app/npmhub/id1542090429).

We still [don't have auto publishing](https://github.com/sindresorhus/refined-github/issues/3686) set up but even having an occasionally-updated version on the App Store would be pretty helpful for most.

**Comment by stefanbuck** [comment]
Sure, I'm in. Thanks for making this possible.
