### ISSUE TITLE
Test click-handler's `fetch` calls

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#311]
https://github.com/OctoLinker/browser-extension/commit/642b4eb47bbcce59df2eb78f2415c539adb8c354#diff-139bc3fd7bb5865bb64075715666a788 removed some tests that ensured the click handler calls `fetch` with the correct arguments (see https://github.com/OctoLinker/browser-extension/pull/306#discussion_r104506996). Ideally, we should re-introduce these tests, perhaps with the help of a tool like:

* https://github.com/speedskater/babel-plugin-rewire
* https://github.com/plasticine/inject-loader

**Comment by stefanbuck** [comment]
Will be resolved once #477 is in place.
