### ISSUE TITLE
Long files aren't completely processed

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#338]
EDIT: See https://github.com/OctoLinker/browser-extension/issues/338#issuecomment-306065970

**Browser name:** Chrome

**Browser version:** Version 57.0.2987.110 (64-bit)

**OctoLinker version:** 1e7ff6fdf34592a2e4b16f03e60a2b3551eceddd

**URL and line number where issue occurs:** https://github.com/angular/core-builds/blob/85cbe3f8d6107af033b0f8b56456c181cbcb5eb7/%40angular/core.js#L3260-L3261

**Expected behavior:** <strike>Either 0 lines or</strike> both lines should get linked

**Actual behavior:** Only the first line gets linked<strike>, but the link doesn't resolve</strike>

<img width="440" alt="screen shot 2017-03-30 at 2 14 28 am" src="https://cloud.githubusercontent.com/assets/6473925/24490091/fe256fb2-14ee-11e7-940b-ceff2ebe218a.png">

**Comment by rgroothuijsen** [comment]
I played around a bit with the sample provided, and strangely enough it did not seem like any particular piece of code triggered the problem. If I cut out  a small section of the file it worked fine, but at a certain workload it seemed like the plugin just died.

**Comment by josephfrazier** [comment]
Thanks for investigating this, @rgroothuijsen. In https://github.com/OctoLinker/browser-extension/pull/365, I added some tests demonstrating that the code itself isn't the issue, and also made it possible to link the packages in the example (at least, the first one).

**Comment by stefanbuck** [comment]
In #774 I added an escape path for files with more than 5000 lines which makes OctoLinker to take just the first 500 lines into account for parsing.

**Comment by stefanbuck** [comment]
Fix will be part of the upcoming version. Release is scheduled for early next week.
