### ISSUE TITLE
Support for symlinks

### ISSUE THREAD

**Issue by tonglil** [OctoLinker/OctoLinker#414]
Often the times there are symlinks committed into the repos, and instead of showing just a file reference, it would be great if that reference was clickable:

**Expected behavior:** 

Example https://github.com/org/repo/blob/master/folder/link.txt with contents:

```
../file.txt
```

Links to https://github.com/org/repo/blob/master/file.txt.

**Actual behavior:** 

N/A

**Comment by josephfrazier** [comment]
Great idea! Here's an example symlink: https://github.com/wmluke/angular-flash/blob/7db7bf177a0908cdc6f2a01d984bd39ea1e3ef1a/app/components
Unfortunately, the target path appears not to exist in the repo, but it's a start

**Comment by fregante** [comment]
This feature was just added to Refined GitHub by the way. Does it work correctly for you? 

https://github.com/sindresorhus/refined-github/pull/2277

**Comment by stefanbuck** [comment]
Closing this request since this feature is supported by Refined GitHub

**Comment by fregante** [comment]
I only added it to Refined GitHub as a stopgap solution until OctoLinker has it, since it’s the more appropriate one 😅 

Maybe https://github.com/OctoLinker/OctoLinker/issues/788 could also take care of this?

**Comment by stefanbuck** [comment]
😄 I see .. in that case I'll extend the issue to include symlinks as well
