### ISSUE TITLE
Support Docker entrypoint

### ISSUE THREAD

**Issue by bfred-it** [OctoLinker/OctoLinker#431]
**OctoLinker version:** 

4.15

Example file: https://github.com/docker-library/wordpress/blob/6a085d90853b8baffadbd3f0a41d6814a2513c11/php5.6/apache/Dockerfile#L59

That `ENTRYPOINT` line could link to https://github.com/docker-library/wordpress/blob/6a085d90853b8baffadbd3f0a41d6814a2513c11/php5.6/apache/docker-entrypoint.sh

**Comment by stefanbuck** [comment]
Should be fairly easy to implement, but I don't have time to work on this right now. I'm busy with refactoring other parts of the app.

Who ever wants to tackle this, there is already a [Docker plugin](https://github.com/OctoLinker/browser-extension/blob/c1f628b0a3e7c55af1d0513fdeb22cf13f3f6ed1/lib/plugins/docker.js) which links the `FROM` field. All what you have to do is adding another REGEX and tweak the resolver similar to https://github.com/OctoLinker/browser-extension/blob/c1f628b0a3e7c55af1d0513fdeb22cf13f3f6ed1/lib/plugins/homebrew-manifest.js

I'm happy to help if there are any questions.

**Comment by MatthewDG** [comment]
Hey team, I'm happy to take this one. PR incoming soon.

**Comment by stefanbuck** [comment]
Available in v4.22.0. @MatthewDG thanks again for adding this feature.
