### ISSUE TITLE
Issues using with OctoTree

### ISSUE THREAD

**Issue by mackeyja92** [OctoLinker/OctoLinker#442]
**Browser name:** 
Firefox Developer Edition
**Browser version:** 
59.9b4
**OctoLinker version:** 
4.16

**URL and line number where issue occurs:** 
No specific page. 

**Expected behavior:** 
When using OctoTree to navigate a repo, OctoLinks should display as normal.

**Actual behavior:** 
When changing pages using OctoTree, OctoLinks are not displayed. Refreshing the page fixes it.

**Comment by stefanbuck** [comment]
Duplicate #416
