### ISSUE TITLE
Composer support broken

### ISSUE THREAD

**Issue by jdreesen** [OctoLinker/OctoLinker#443]
**Browser name:** Firefox

**Browser version:** 58.0.1 (64-Bit)

**OctoLinker version:** 4.16.0

**URL and line number where issue occurs:** 
right now: https://github.com/matthiasnoback/behat-local-code-coverage-extension/blob/master/composer.json#L6
but it occurs on every `composer.json` file since a while

**Expected behavior:** A new tab for the package opens

**Actual behavior:** Nothing happens

![grafik](https://user-images.githubusercontent.com/424602/35940828-b5870dec-0c50-11e8-8156-86f776342d99.png)

**Comment by stefanbuck** [comment]
Looks like my giant refactoring #436 cause this issue, sorry for that. Will fix it asap.

**Comment by jdreesen** [comment]
Thx for the quick fix! I absolutely love this addon :)

**Comment by stefanbuck** [comment]
New version `v4.16.1` is out.

**Comment by jdreesen** [comment]
I just updated and it works again, thx ❤️
