### ISSUE TITLE
Deprecation of jQuery 2.x in Firefox add-ons

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#446]
I just got this email from Mozilla, and I'm pretty sure it's referring to OctoLinker, since I don't have any other addons on AMO. However, I can't seem to find where jQuery 2.x is used in OctoLinker...

> Hello,
>
> You’re receiving this message because you’re an add-on developer registered on AMO (addons.mozilla.org) and and you are using jQuery 2.x in at least one of your add-ons. We want to inform you about the upcoming deprecation of that version.
>
> jQuery 2.x is no longer maintained and contains vulnerabilities that could lead to security issues in add-ons. Effective immediately, the validation process will warn you if jQuery 2.x is found during the submission of a new version or add-on. After September 1, 2018, no new submissions using jQuery 2.x will be accepted.
>
> Please upgrade to jQuery 3.x as soon as possible. Refer to the upgrade guide at https://jquery.com/upgrade-guide/3.0/ for more information.
>
> Regards,
>
> The Add-ons Team
>
> You have received this email because you are a registered add-on developer on addons.mozilla.org and you are using the jQuery 2.x in at least one of your extensions. If you do not want to receive these updates about your AMO account and your use of jQuery 2.x, please sign in to addons.mozilla.org and disable your add-ons that use jQuery 2.x.

**Comment by stefanbuck** [comment]
Thanks for the heads up. I found this email in my spam folder 😆 so it must be OctoLinker. It think it's false alert from their side. I checked the build file and there is definitely no jQuery 2.x. I'll write them and ask for clarification.

**Comment by stefanbuck** [comment]
Resolved, octolinker will stay https://discourse.mozilla.org/t/deprecation-of-jquery-2-x/25724/4

**Comment by josephfrazier** [comment]
Glad to hear it, thanks for following up with Mozilla!
