### ISSUE TITLE
Not all supported NuGet references are being linkified

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#449]
**Browser name:** Chrome

**Browser version:** 64

**OctoLinker version:** 4.16.1

**URL and line number where issue occurs:** https://github.com/equineexchange/EquineExchange.ImageHosting/commit/3a917291b3e2ad459d2ed84af96b6245658758bf#diff-f2c1409a20722ddaf5705add38f2fbe1

**Expected behavior:** The NuGet packages should be linkified like they are elsewhere such as https://github.com/equineexchange/EquineExchange.ImageHosting/commit/de36584935a5bc47b3c4f732af289f75aa4581da#diff-f2c1409a20722ddaf5705add38f2fbe1

**Actual behavior:** The NuGet packages are not linkified like they are in other diffs

I've worked on the NuGet references but I don't have the time right now to look into this. I wanted to report it in case someone else might know what's causing the issue.

I've been noticing this in a lot of my recent PR diffs. Sometimes the diff will contain say 8 files that contain NuGet package references, but only 2 or 3 of them will actually be linkified. In other cases all the files are. It's happening in both my `packages.config` and `*.csproj` files.

**Comment by stefanbuck** [comment]
Maybe related to #338

**Comment by leomoty** [comment]
This one is very strange, opening the URL yields no octolinks whatsoever. but clicking View in `packages.config` and then pressing `history back`, it works. @stefanbuck any hints here?

**Comment by leomoty** [comment]
Hello @stefanbuck, @josephfrazier,

I have been quite busy at work, but got a bit of time today, I figured out the issue, it might be related to #338.

It is not an OctoLinker issue per se, we are handling it fine, however, some blobs are not loaded with the document. This is loaded by javascript afterwards:

https://github.com/equineexchange/EquineExchange.ImageHosting/diffs?bytes=17873&commentable=true&commit=3a917291b3e2ad459d2ed84af96b6245658758bf&lines=372&sha1=5d20a77c8f23b17b181ee84bb425395a8414bb2f&sha2=3a917291b3e2ad459d2ed84af96b6245658758bf&start_entry=10



If you disable javascript you'll see this:

![image](https://user-images.githubusercontent.com/1463740/46261921-c27cca80-c4d0-11e8-96f0-034277e960de.png)

I don't know the best solution, but we need either to defer the `octolinker.init()` call or do something like we did with #505.

A friend suggested something alongside these lines: https://gist.github.com/BrockA/2625891, we might need to rethink BlobReader to not visit the same blobs over and over, could even benefit #505?

**Comment by xt0rted** [comment]
GitHub uses [selector-observer](https://github.com/josh/selector-observer) to wire up their JS because of how parts of the site load (mostly PJAX). I'm not familiar with how Octolinker is setup but maybe this pattern is what's needed to get these other sections to work?

**Comment by stefanbuck** [comment]
It should re-run on `pjax:end`, but maybe they changed the way how the lazy load snippets and `pjax:end` isn't invoked anymore. 

https://github.com/OctoLinker/injection/blob/master/index.js#L12

**Comment by leomoty** [comment]
Yeah I noticed that as well.

**Comment by leomoty** [comment]
Also that being the case, when you expand a deleted file, the content wont get octolinked, right?

**Comment by stefanbuck** [comment]
Seems to be working fine now. Feel free to reopen the issue in case it's still an issue
