### ISSUE TITLE
Adding relative project linking for .net projects

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#450]
Since .NET projects can reference one another I wanted to see about adding project file linking, similar to the [imports in less or sass files](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_mixins.scss). An example of this in a `.csproj` can be seen at [Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L21-L23](https://github.com/aspnet/AzureIntegration/blob/f7689a10addae8a12bf84699822da155d90db788/extensions/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L21-L23)

I was looking at the existing code that does this, but I'm not sure if this can be added to the existing .net integration that handles NuGet package references. The NuGet packages in `.csproj` files come from `PackageReference` nodes while projects use `ProjectReference`.

Got any advice for how to tackle this one?

**Comment by stefanbuck** [comment]
If I understand you correctly, you're asking how you can differentiate between different resolvers within the same plugin, right?

The JavaScript plugin does this [with a RegExp](https://github.com/OctoLinker/OctoLinker/blob/03cf6a2639bfbdc35b7d3fc89627dafdb7f7b2e3/packages/plugin-javascript/index.js#L65) on the `target` argument. Based on the result it calls either the `javascriptFile` or `liveResolverQuery` resolver function.

**Comment by xt0rted** [comment]
Finally got around to adding in support for this. I have it working but need to add some tests. I'll try to get a PR in over the weekend for review.
