### ISSUE TITLE
Line indicator is misaligned and cutoff in pull requests

### ISSUE THREAD

**Issue by xPaw** [OctoLinker/OctoLinker#452]
**Browser name:** Chrome
**Browser version:** 66.0.3355.0
**OctoLinker version:** 4.16.1

1. In PR review comments, the dot is aligned on top of the comment container, not on the line ([link](https://github.com/thelounge/thelounge/pull/1839#pullrequestreview-100691286))

![03-161286724](https://user-images.githubusercontent.com/613331/36936462-909805ce-1f0e-11e8-85ac-11106378bdb0.png)

2. In diff view the indicator is cut off ([link](https://github.com/thelounge/thelounge/pull/1839/files#diff-cf27c1d543e886c89cd9ac8b8aeaf05b))

![03-161346687](https://user-images.githubusercontent.com/613331/36936471-abadf044-1f0e-11e8-9000-180a470b5571.png)

**Comment by stefanbuck** [comment]
Mhhh looks good to me ... maybe they reverted some of the changes. @xPaw is this still an issue for you?

<img width="512" alt="screen shot 2018-03-05 at 22 06 53" src="https://user-images.githubusercontent.com/1393946/36999805-8f363098-20c1-11e8-83f1-0fe89dcc5a37.png">
<img width="528" alt="screen shot 2018-03-05 at 22 07 01" src="https://user-images.githubusercontent.com/1393946/36999806-8f51f42c-20c1-11e8-9aba-ce76d41028bd.png">

**Comment by xPaw** [comment]
Hah, you are right, it looks fine now.
