### ISSUE TITLE
Process loaded code when expanding diff views

### ISSUE THREAD

**Issue by xPaw** [OctoLinker/OctoLinker#453]
Link: https://github.com/thelounge/thelounge/pull/1839/files#diff-cf27c1d543e886c89cd9ac8b8aeaf05b

Hopefully the GIF explains what I mean:
![03-161708105](https://user-images.githubusercontent.com/613331/36936512-3e3688fe-1f0f-11e8-8428-9bf3f13d3a06.gif)

**Comment by josephfrazier** [comment]
This sounds related to https://github.com/OctoLinker/OctoLinker/issues/416, since they both concern page changes that don't trigger reprocessing.

**Comment by xPaw** [comment]
I'm not sure that's entirely related, as your linked issue concerns navigation (pjax), while this changes the page state without navigation.

**Comment by stefanbuck** [comment]
I agree with @xPaw. This issue is slightly different. It should be relative easy to fix. 

We're happy to provide mentor help for people who want to pick this up.

**Comment by leomoty** [comment]
Hey @stefanbuck, any pointers for this one?

**Comment by stefanbuck** [comment]
At its core, it's just about calling `run` which will basically re-invoke the whole extension. 

https://github.com/OctoLinker/OctoLinker/blob/e218001fe64a9864e8f90994f406d3b588802702/packages/core/octo-linker.js#L20

**Comment by leomoty** [comment]
@stefanbuck I have a preliminary version working with MutationObserver, I am looking for addedNodes that contains `.blob-expanded`, if that is the case, run `run` again. Should this be a function in `octo-linker.js`, or something? I can make a PR tomorrow.

**Comment by stefanbuck** [comment]
Great news 👍 Yes, putting that into `octo-linker.js` sounds appropriate to me. Regarding testing, recently I added [E2E testing](https://github.com/OctoLinker/OctoLinker/tree/master/e2e) which should make testing such behaviour much easier. Literally, it's just click and inspecting the DOM for new `.octolinker-link` elements. I'm happy to help you if you get stuck.
