### ISSUE TITLE
Commit comment elements are being parsed as dependencies and turned into links

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#454]
**Browser name:** Chrome

**Browser version:** 65

**OctoLinker version:** 4.16.1

**URL and line number where issue occurs:** https://github.com/github/octodns/pull/139/files#r148934041

**Expected behavior:** UI elements such as the `Contributor` label and `edited` drop down should not be treated as a package dependency.

**Actual behavior:** These elements are incorrectly parsed as dependencies and turned into links with purple dot indicators next to them.

![image](https://user-images.githubusercontent.com/831974/37566775-09b3e12c-2a94-11e8-9b06-2105c6ceb12f.png)

![image](https://user-images.githubusercontent.com/831974/37566754-c9bb22a6-2a93-11e8-9d54-00168677f263.png)

**Comment by stefanbuck** [comment]
#774 is fixing this as well 😄

**Comment by stefanbuck** [comment]
Fix will be part of the upcoming version. Release is scheduled for early next week.
