### ISSUE TITLE
Interpret .json as .js

### ISSUE THREAD

**Issue by StarpTech** [OctoLinker/OctoLinker#455]
**Browser name:** 
Chrome
**Browser version:** 
Version 65.0.3325.181 (Offizieller Build) (64-Bit)
**OctoLinker version:** 
4.16.1
**URL and line number where issue occurs:** 
https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L10
**Expected behavior:** 
Redirect to `'./schemas.json`
**Actual behavior:** 
Redirect to `'./schemas.js`

**Comment by leomoty** [comment]
That URL is not valid anymore:

https://github.com/fastify/fastify/blob/93fcef0a2b49423b9be6142a9b16a9db760a43fd/lib/handleRequest.js#L10

Also, this seems to work fine on master.

**Comment by StarpTech** [comment]
Yes, seems to work with the latest update. Thanks.
