### ISSUE TITLE
Firefox: version compatibilty

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/OctoLinker#468]
**Browser name:** Firefox
**Browser version:** 56
**OctoLinker version:** 4.17.1

I noticed that 4.17.0 or greater do not work on Firefox 56 (Links are added but nothing happens on click).

The compatibilty info for 4.17.0 and 4.17.1 [here]( https://addons.mozilla.org/en-US/firefox/addon/octolinker/versions/) says "Works with Firefox 47.0 and later", maybe it should be updated to say "Works with Firefox 57.0 and later".

**Comment by stefanbuck** [comment]
I updated the compatibility to `57.0 and later` as you suggested. Thanks for reporting!
