### ISSUE TITLE
Support js import in vue component

### ISSUE THREAD

**Issue by maple3142** [OctoLinker/OctoLinker#496]
**Browser name:** 
CentBrowser

**Browser version:** 
3.5.3.50 (Chromium 67.0.3396.99)

**OctoLinker version:** 
4.20.0

**URL and line number where issue occurs:** 
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/components/Item.vue#L30

**Expected behavior:** 
The import is clickable.

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/9370547/44089626-118f95fe-9ffa-11e8-8d9c-d93cff938d9b.png)

**Comment by stefanbuck** [comment]
Should be fairly easy to implement by tweaking those three lines:

https://github.com/OctoLinker/OctoLinker/blob/5a104cf88b4cd260f3b788500ecc99feb0f2ae18/packages/plugin-javascript/index.js#L23

https://github.com/OctoLinker/OctoLinker/blob/5a104cf88b4cd260f3b788500ecc99feb0f2ae18/packages/plugin-javascript/index.js#L91

https://github.com/OctoLinker/OctoLinker/blob/5a104cf88b4cd260f3b788500ecc99feb0f2ae18/packages/plugin-javascript/index.js#L97

**Comment by stefanbuck** [comment]
It has just landed on master #499
