### ISSUE TITLE
yarn *-open commands

### ISSUE THREAD

**Issue by leomoty** [OctoLinker/OctoLinker#507]
**Intended outcome:**

Running `yarn chrome-open` should open a chrome session with the extension loaded

**Actual outcome:**

Complains about an issue with the manifest

**How to reproduce the issue:**

Run `yarn chrome-open`

----

`yarn firefox-open` on other hand seems to work fine, but OctoLinker is not injected properly in some pages, like the diff view.

**Comment by josephfrazier** [comment]
Hi @leomoty, thanks for the report!

Could you post the error you're seeing, along with your `node` and `yarn` versions?

I just tried `yarn chrome-open` on a machine running Node v8.11.3 and Yarn v1.7.0, and got the chrome session with the extension loaded, as expected. For what it's worth, the output looked like this:

<details><summary>Click to show output</summary>

```
josephfrazier@Josephs-MacBook-Pro:~/workspace/OctoLinker$ yarn chrome-open
yarn run v1.7.0
$ yarn build && yarn chrome-launch --
$ webpack --mode=production
Hash: ce8a36c73a11f5f68b99
Version: webpack 4.8.1
Time: 7248ms
Built at: 2018-08-28 18:36:51
        Asset       Size  Chunks                    Chunk Names
   options.js    131 KiB       0  [emitted]         options
background.js   7.41 KiB       1  [emitted]         background
       app.js    372 KiB       2  [emitted]  [big]  app
manifest.json  889 bytes          [emitted]
 options.html  125 bytes          [emitted]
     icon.png   13.6 KiB          [emitted]
Entrypoint app [big] = app.js
Entrypoint background = background.js
Entrypoint options = options.js
 [2] ./packages/helper-settings/index.js 839 bytes {0} {1} {2} [built]
[10] (webpack)/buildin/global.js 509 bytes {2} [built]
[28] ./packages/core/background/index.js + 1 modules 441 bytes {1} [built]
     | ./packages/core/background/index.js 131 bytes [built]
     | ./packages/core/background/newTab.js 305 bytes [built]
[29] ./packages/helper-settings/page.js + 5 modules 23.1 KiB {0} [built]
     | ./packages/helper-settings/page.js 2.39 KiB [built]
     |     + 5 hidden modules
[30] ./packages/core/app.js + 52 modules 54.2 KiB {2} [built]
     | ./packages/core/plugin-manager.js 2.03 KiB [built]
     | ./packages/core/app.js 191 bytes [built]
     | ./packages/blob-reader/index.js 301 bytes [built]
     | ./packages/helper-insert-link/index.js 4.16 KiB [built]
     | ./packages/helper-sort-urls/index.js 421 bytes [built]
     | ./packages/core/notification.js 845 bytes [built]
     | ./packages/core/click-handler.js 2.68 KiB [built]
     | ./packages/core/octo-linker.js 1.99 KiB [built]
     | ./packages/core/debug-mode.js 129 bytes [built]
     | ./packages/core/load-plugins.js 1.51 KiB [built]
     | ./packages/blob-reader/helper.js 3.78 KiB [built]
     | ./packages/core/utils/fetch.js 802 bytes [built]
     | ./packages/core/gh-interface.js 1.05 KiB [built]
     | ./packages/core/utils/array.js 93 bytes [built]
     | ./packages/plugin-vim/index.js 1.25 KiB [built]
     |     + 38 hidden modules
[35] ./node_modules/css-loader!./packages/helper-settings/style.css 347 bytes {0} [built]
[36] ./packages/helper-settings/style.css 1020 bytes {0} [built]
[43] ./packages/core/package.json 1.49 KiB {2} [built]
[44] ./node_modules/css-loader!./packages/helper-insert-link/style.css 943 bytes {2} [built]
[45] ./packages/helper-insert-link/style.css 1020 bytes {2} [built]
[50] (webpack)/buildin/module.js 519 bytes {2} [built]
    + 42 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.js (372 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (372 KiB)
      app.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node scripts/chrome-launch.js
A new instance of Chrome should now be open in the background.
```

</details>

**Comment by leomoty** [comment]
Hello @josephfrazier, no problem.

```
C:\Users\leomoty>node --version
v10.8.0

C:\Users\leomoty>yarn --version
1.9.4
```

<details>
<summary>yarn chrome-open output</summary>
<pre>
C:\Users\leomoty\Documents\Projects\OctoLinker>yarn chrome-open
yarn run v1.9.4
$ yarn build && yarn chrome-launch --
$ webpack --mode=production
Hash: bb49aa6dfc0b7bde3365
Version: webpack 4.8.1
Time: 2455ms
Built at: 2018-08-28 19:50:10
        Asset       Size  Chunks                    Chunk Names
   options.js    131 KiB       0  [emitted]         options
background.js   7.41 KiB       1  [emitted]         background
       app.js    372 KiB       2  [emitted]  [big]  app
 options.html  125 bytes          [emitted]
manifest.json  935 bytes          [emitted]
     icon.png   13.6 KiB          [emitted]
Entrypoint app [big] = app.js
Entrypoint background = background.js
Entrypoint options = options.js
 [2] ./packages/helper-settings/index.js 839 bytes {0} {1} {2} [built]
[10] (webpack)/buildin/global.js 509 bytes {2} [built]
[28] ./packages/core/background/index.js + 1 modules 441 bytes {1} [built]
     | ./packages/core/background/index.js 131 bytes [built]
     | ./packages/core/background/newTab.js 305 bytes [built]
[29] ./packages/helper-settings/page.js + 5 modules 23.1 KiB {0} [built]
     | ./packages/helper-settings/page.js 2.39 KiB [built]
     |     + 5 hidden modules
[30] ./packages/core/app.js + 52 modules 54.5 KiB {2} [built]
     | ./packages/core/plugin-manager.js 2.03 KiB [built]
     | ./packages/core/app.js 191 bytes [built]
     | ./packages/blob-reader/index.js 301 bytes [built]
     | ./packages/helper-insert-link/index.js 4.16 KiB [built]
     | ./packages/helper-sort-urls/index.js 421 bytes [built]
     | ./packages/core/notification.js 845 bytes [built]
     | ./packages/core/click-handler.js 2.68 KiB [built]
     | ./packages/core/octo-linker.js 2.23 KiB [built]
     | ./packages/core/debug-mode.js 129 bytes [built]
     | ./packages/core/load-plugins.js 1.51 KiB [built]
     | ./packages/blob-reader/helper.js 3.78 KiB [built]
     | ./packages/core/utils/fetch.js 802 bytes [built]
     | ./packages/core/gh-interface.js 1.05 KiB [built]
     | ./packages/core/utils/array.js 93 bytes [built]
     | ./packages/plugin-vim/index.js 1.25 KiB [built]
     |     + 38 hidden modules
[35] ./node_modules/css-loader!./packages/helper-settings/style.css 347 bytes {0} [built]
[36] ./packages/helper-settings/style.css 1020 bytes {0} [built]
[43] ./packages/core/package.json 1.53 KiB {2} [built]
[44] ./node_modules/css-loader!./packages/helper-insert-link/style.css 943 bytes {2} [built]
[45] ./packages/helper-insert-link/style.css 1020 bytes {2} [built]
[50] (webpack)/buildin/module.js 519 bytes {2} [built]
    + 42 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.js (372 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (372 KiB)
      app.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node scripts/chrome-launch.js
A new instance of Chrome should now be open in the background.
Done in 59.53s.
</pre>
</details>

It doesn't seem to log to the console, chrome opens with an alert window with this content:

```
---------------------------
Erro ao carregar extensão
---------------------------
Falha ao carregar a extensão a partir de: C:\Program Files (x86)\Google\Chrome\Application\68.0.3440.106\dist. O arquivo de manifesto está faltando ou não pode ser lido
---------------------------
OK   
---------------------------
```

Title: Failed to load the extension
Error: Manifest file is missing or unreadable

**Comment by stefanbuck** [comment]
I'm using node 10.9 with yarn 1.9.4 and it is working. Maybe this is a windows related issue.

**Comment by leomoty** [comment]
Seems likely yes, since it is trying to serve `dist` from Google Chrome's directory.

**Comment by leomoty** [comment]
I can confirm that it works by adjusting this line:

https://github.com/OctoLinker/OctoLinker/blob/master/scripts/chrome-launch.js#L6
