### ISSUE TITLE
Whitespace in dockerfile image links should be ignored

### ISSUE THREAD

**Issue by steebchen** [OctoLinker/OctoLinker#515]
**Intended outcome:**

Clicking on a `FROM image` link with whitespace between the FROM and the image in a Dockerfile and getting redirected to the correct docker hub link.

**Actual outcome:**

There was whitespace between the FROM and the image name, thus I was redirected to an url like `https://hub.docker.com/_/%20%20%20%20%20%20%20ubuntu/` where %20 stands for whitespace (a space).

**How to reproduce the issue:**

Click on the FROM in the [ffmpeg 4.0 dockerfile](https://github.com/jrottenberg/ffmpeg/blob/master/docker-images/4.0/ubuntu/Dockerfile#L8)

![selection_999 109](https://user-images.githubusercontent.com/5013932/45927315-d30dcd80-bf31-11e8-9781-be203efd17c1.jpg)

**Comment by stefanbuck** [comment]
This should be fairly easy to fix by tweaking the related Docker RegExp

https://github.com/OctoLinker/OctoLinker/blob/a0cab84c5adfdfea10a819ba07030946c6c356de/packages/helper-grammar-regex-collection/index.js#L73

**Comment by MatthewDG** [comment]
I'm happy to take this on unless you wanted to go for it @steebchen

**Comment by steebchen** [comment]
Feel free to. I tried to look into this but I just don't get this special xregexp stuff and \s just seems fine.. :P
