### ISSUE TITLE
Start processing the link on hover / speculatively

### ISSUE THREAD

**Issue by rauchg** [OctoLinker/OctoLinker#530]
In most cases, we should not have to see the popover and read "Processing". That should be more of a worst case scenario.

**Comment by stefanbuck** [comment]
I agree with you. This has been raised a few times already #277. I'm currently working on a fix. A first version to prefetch external links in the background went out a few hours ago. I'm using shadow loading to see the real production load on my Heroku plan. You still get the popover, but you will be redirected immediately after a click on e.g. `require('lodash')`. Relative files are not affected by this change yet.

**Comment by rauchg** [comment]
@stefanbuck if it fits a serverless architecture, I'd love to host you on [Now](https://zeit.co/now) and sponsor this project. I love it.

**Comment by stefanbuck** [comment]
Thanks @rauchg that's a generous offer. 

With a few tweaks the service should be serverless ready. It's a bunch of handlers and a few static assets to support java resolution. We use serverless for some internal tooling at work, but I never used serverless in production. Therefore I have some thoughts.

I'm little bit worried how to achieve caching in a serverless environment. Right now, the service stores all resolved url in memory. This was working fine in the past where the service was just requested on click. With the recent mentioned changes every browser navigation is prefetch links in the background. As expected this put a lot of traffic on the service and caused some serious memory issues. 

Also I wonder about the cost factor putting a service into serverless which 
(according to New Relic) handled 36.2K request within the last 24 hours. 

However, I would like to give `Now` a try. I'm really attracted by the fact to be able to deploy the service in different regions. Right now it's hosted in the US wich isn't ideal.

**Comment by josephfrazier** [comment]
Oh man, I would love to be able to have this on Now! I've been keeping an eye on Now for a while, and I keep liking it more and more, but haven't actually used it for anything.

**Comment by stefanbuck** [comment]
I've gotten the bare minimum (npm only) working here https://octolinker.now.sh/?package=lodash There is still some work left to do, but once it's complete I'll send a subset of users over to see how the service behaves in a serverless environment.

**Comment by stefanbuck** [comment]
This will be fixed in the next major release which is scheduled for end of April. In case you don't want to wait, a beta version is available here https://github.com/OctoLinker/OctoLinker/issues/549

Thanks again for sponsoring OctoLinker. It was fun project to move the service over to NOW.
