### ISSUE TITLE
Doesn't work with lerna-style repositories

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/OctoLinker#535]
**Intended outcome:**

I clicked a link to the `jest-mock` package and expected to be taken to https://github.com/facebook/jest/tree/master/packages/jest-mock

**Actual outcome:**

I was taken to https://github.com/facebook/jest instead

**How to reproduce the issue:**

Go here and click `jest-mock`: https://github.com/facebook/jest/blob/f13b97b70238ee8cd973632d243d046e0f8e794b/types/Mock.js#L13

---

[Lerna] is growing in popularity, so we should check to see if (for example) the `tree/master/packages/jest-mock` URL works, and go to it instead of the repo root if possible. I'll probably try to fix this myself, but wanted to make an issue for it, for reference.

[Lerna]: https://lernajs.io/

**Comment by xt0rted** [comment]
@stefanbuck this looks to be working now.

**Comment by stefanbuck** [comment]
Yup, I know. I added the logic earlier this year and forgot to close this issue https://github.com/OctoLinker/api/commit/f87103c72ff3fbf78b9c49c1a8ab739f75b0f179 Thanks for the reminder
