### ISSUE TITLE
Links not working in certain package.json files

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/OctoLinker#539]
**Intended outcome:**

Links in https://github.com/sindresorhus/got/blob/master/package.json should work.

**Actual outcome:**

None of the links in the file work. While the individual dependency names do turn into links, clicking on them does nothing. No errors are visible in the browser console.

**How to reproduce the issue:**

Use OctoLinker 4.22.5 on Firefox 64.0.2 and open above linked package.json.

**Comment by stefanbuck** [comment]
Fixed and released!
