### ISSUE TITLE
Not fully redirecting

### ISSUE THREAD

**Issue by OrangutanGaming** [OctoLinker/OctoLinker#545]
**Intended outcome:**
When you click a link, it should redirect to the url

**Actual outcome:**
It redirects to `https://githublinker.herokuapp.com/...` and simply shows a JSON

**How to reproduce the issue:**
Click a link, had it happen on every link

Using Chrome 73.0.3683.75 (Official Build) beta (64-bit) and OctoLinker 4.22.6

**Comment by stefanbuck** [comment]
Can you provide a link to the page that is causing this problem. That would be really helpful.

**Comment by OrangutanGaming** [comment]
Just narrowed it down slightly, it seems to be on any Python file

**Comment by OrangutanGaming** [comment]
Also getting it on Dockerfiles

**Comment by stefanbuck** [comment]
The linking works for all links in this file https://github.com/pallets/flask/blob/master/flask/cli.py

**Comment by stefanbuck** [comment]
This Docker file works as well for me https://github.com/OctoLinker/OctoLinker/blob/master/e2e/fixtures/docker/Dockerfile

**Comment by stefanbuck** [comment]
Without an example link it's really hard to narrow down the issue.

**Comment by OrangutanGaming** [comment]
With both of those links it's not working, must be something on my end

**Comment by stefanbuck** [comment]
Are you using Chrome or Firefox?

**Comment by OrangutanGaming** [comment]
>Using Chrome 73.0.3683.75 (Official Build) beta (64-bit) and OctoLinker 4.22.6

**Comment by stefanbuck** [comment]
I was still on 72, but after updating to 73 I get the same result.

**Comment by stefanbuck** [comment]
Chrome 73 changed to cross-origin requests in chrome extension content scripts see 
https://www.chromestatus.com/feature/5629709824032768

**Comment by stefanbuck** [comment]
Fixed and released. An update should be available within 30min. New version will be v4.22.7
