### ISSUE TITLE
Add support for `CODEOWNERS` (and other local paths)

### ISSUE THREAD

**Issue by fregante** [OctoLinker/OctoLinker#550]
ExampleS where linked files would be useful:

- https://github.com/sindresorhus/refined-github/blob/master/.github/CODEOWNERS
- https://github.com/sindresorhus/refined-github/blob/master/.gitattributes

**Comment by stefanbuck** [comment]
I opened another issue for the local path request https://github.com/OctoLinker/OctoLinker/issues/788
