### ISSUE TITLE
Middle click scrolling

### ISSUE THREAD

**Issue by Logerfo** [OctoLinker/OctoLinker#553]
I don't think #173 is working as it's supposed to. When I middle-click a link, it opens in a new tab, but the "auto scrolling" browser feature gets activated as well. The intended behavior was supposed to be the auto scroll being cancelled.

**Comment by stefanbuck** [comment]
Thanks for reporting. This indeed sounds like a bug. However a new major release will be available soon which I think will solve this issue as well. Do you mind to give the beta version a try and report back in this? That would be really helpful. Thanks https://github.com/OctoLinker/OctoLinker/issues/549

**Comment by Logerfo** [comment]
Yes, it works as expected in the beta version. Thanks!
