### ISSUE TITLE
Support for Go Modules

### ISSUE THREAD

**Issue by Albert221** [OctoLinker/OctoLinker#554]
Example file: https://github.com/mattermost/mattermost-server/blob/master/go.mod

**Comment by stefanbuck** [comment]
Actually OctoLinker is already supporting go see https://github.com/kubernetes/ingress-gce/blob/6f8bdc9fad1b5576d4fe07900301a133652a8892/cmd/glbc/main.go#L31 

In your given example the file extension is `.mod` which is the reason why OctoLinker didn't started to resolve links. Is this a common extension for certain go files?

**Comment by stefanbuck** [comment]
Ahh that's a new manifest like file similuar to package.json https://github.com/golang/go/wiki/Modules#gomod Shoudl be easy to add support for it. Are you intressted in submitting a PR? I'm more than happy to help you landing this feature.

**Comment by StarpTech** [comment]
I prepared https://github.com/OctoLinker/OctoLinker/pull/845 would be great to have some reviewers.
