### ISSUE TITLE
Unclickabe file links

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/OctoLinker#574]
**Intended outcome:** Links in [this file](https://github.com/emailjs/emailjs-tcp-socket/blob/master/src/socket.js) should open the respective files in the same directory
**Actual outcome:** Files are linkified but unclickable.
**How to reproduce the issue:** Open above URL and try clicking `./node-socket`

Maybe because they are missing the `.js` extension? (Node.js automatically adds `.js,.json,.node,.mjs` if missing). You can detect these cases if a `require` or `import` argument matches `\.\/.+`.

**Comment by stefanbuck** [comment]
Strange works for me. Maybe another Firefox issue!? I'll look into this later today

**Comment by silverwind** [comment]
Yes, this was Firefox on Windows. Just tested again on Firefox and Chrome on Mac and both were, so I assume it's something about my installation, will try with a fresh profile later and reopen if necessary.
