### ISSUE TITLE
package name in a js template literal disappears

### ISSUE THREAD

**Issue by sodatea** [OctoLinker/OctoLinker#590]
**Intended outcome:**

The template literal remains untouched.

**Actual outcome:**

```
`import foo from 'foo'`
```
became
```
`import foo from '`
```
after this extension is enabled

**How to reproduce the issue:**

https://github.com/vuejs/vue-cli/blob/77c7c66922fe2d007ed2094db5441ebc18ca825d/packages/%40vue/cli/__tests__/Generator.spec.js#L526

**Comment by stefanbuck** [comment]
#774 is fixing this as well 😄

**Comment by stefanbuck** [comment]
Fix will be part of the upcoming version. Release is scheduled for early next week.
