### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by MarkTiedemann** [OctoLinker/OctoLinker#613]
```typescript
import * as fs from "https://deno.land/std/fs/mod.ts";
```

..., for example, should link to [https://deno.land/std/fs/mod.ts](https://deno.land/std/fs/mod.ts) rather than [https://www.npmjs.com/package/https](https://www.npmjs.com/package/https).

**Comment by stefanbuck** [comment]
How do I know that this is a Deno import? It's using regular typescript so hard to tell whether this is node or Deno.

**Comment by MarkTiedemann** [comment]
Right, Deno compatible JavaScript or TypeScript files are not marked in any special way.

However, there are two distinctions here:

- In Node, `require("module")` or `require("./file")` doesn't need an extension. In Deno, `.js` or `.ts` is mandatory.
- Unlike in Deno, in Node, you cannot import from a URL, e.g. `http://example.org/module.ts` or `https://example.org/module.ts`.

So I guess, based on that, if a file with a proper extension is imported from a URL, instead of linking to the `http` or `https` NPM modules, you could link to the respective file instead.

But yeah, I'm not a 100% certain either.

**Comment by MarkTiedemann** [comment]
On another note, I believe that `import { foo } from "https://example.org/bar.js";` is already supported in a `<script type="module">` (see:
https://jakearchibald.com/2017/es-modules-in-browsers/#bare-import-specifiers-arent-currently-supported). This isn't really a new invention by Deno but rather Deno trying to follow web standards.

**Comment by stefanbuck** [comment]
I'm happy to pair up with you to get this feature landed, but I don't have time to implement it by myself right now.

**Comment by MarkTiedemann** [comment]
Okay, sure. I'll take a stab at implementing this feature in the next few days.
