### ISSUE TITLE
Inconsistent linking

### ISSUE THREAD

**Issue by fregante** [OctoLinker/OctoLinker#618]
**Intended outcome:**

Either always link the variable or always link the package name

**Actual outcome:**

Sometimes is the variable, sometimes it's the package

![d](https://user-images.githubusercontent.com/1402241/62033157-8b249a80-b215-11e9-8715-4feb67d8ca60.gif)

**How to reproduce the issue:**
1. Visit:  https://github.com/OctoLinker/OctoLinker/blob/master/_jestsetup.js
2. Notice linking of imports

Tested in Chrome and Firefox

**Comment by stefanbuck** [comment]
Thanks for filling this issue. This is indeed a bug probably located somewhere in [helper-insert-link](https://github.com/OctoLinker/OctoLinker/blob/master/packages/helper-insert-link/index.js). That's the most tricky part of OctoLinker 🙈 I'll look into it.

**Comment by fregante** [comment]
This would probably require a rewrite, but if you're looking for an alternative way to do replacements, have a look at [fregante/zip-text-nodes](https://github.com/fregante/zip-text-nodes) 

I think this would let you do parsing and replacement in one go (per parser). Example:

```jsx
function linkifyFile(fileDom, regex, getDependencyURL) {
	// Turns current file (string) into DocumentFragment with links
	const linkified = fileDom.textContent
		.split(regex)
		.reduce((fragment, text, index) => {
			if (index % 2) { // Keywords will be in odd positions
				fragment.append(<a href={getDependencyURL(text)}>{text}</a>);
			} else if (text.length > 0) {
				fragment.append(text);
			}
	
			return fragment;
		}, document.createDocumentFragment());
	
	if (linkified.children.length === 0) { // Children are <a>
		return;
	}
	
	// Links and syntax-highlighted DOM will be merged here
	zipTextNodes(fileDom, linkified);
}
```

Real-life example: 
- linkifier: https://github.com/sindresorhus/linkify-urls/blob/62fd87c59d61eb8d15530e4d38dbc99abdef78b6/index.js#L27-L37
- replacer (with `zip-text-nodes`): https://github.com/sindresorhus/refined-github/blob/1d180ef1005d91199419fd9fdc771fee62a235b5/source/libs/dom-formatters.ts#L46-L64

**Comment by stefanbuck** [comment]
As you know I'm just about to finish another bigger refactoring 😆 Anyway I'll give this a shot at some point

**Comment by fregante** [comment]
I don't make promises about its performance though, before you ever use it perhaps try it on a long file first.

**Comment by QSASPTYLTD** [comment]
STOP TEPLYING TO CALVIN . This encryption stuff is destroying my family

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stefanbuck** [comment]
#774 fixes this issue too 😄

**Comment by stefanbuck** [comment]
Fix will be part of the upcoming version. Release is scheduled for early next week.
