### ISSUE TITLE
Wrong linking

### ISSUE THREAD

**Issue by darkred** [OctoLinker/OctoLinker#627]
**Intended outcome:**

Go to https://github.com/sindresorhus/refined-github/blob/master/source/background.ts#L1 .
Hover mouse over `webext-dynamic-content-scripts` :
Octolinker should linkify to: 
`https://github.com/fregante/webext-dynamic-content-scripts`

**Actual outcome:**

Instead it linkifies to: 
`https://github.com/fregante/webext-additional-permissions`, i.e. 

![2019-08-03_124016](https://user-images.githubusercontent.com/723651/62410243-ebd41e80-b5eb-11e9-945c-0a4b155a7f96.jpg)

**How to reproduce the issue:**

Follow the above steps in a fresh Chrome 76/Firefox 68 profile, with only Octolinker 5.0.2 installed.

**Comment by stefanbuck** [comment]
OctoLinker gets the URL from the package.json which seems to be wrong. 

https://github.com/fregante/webext-dynamic-content-scripts/blob/master/package.json#L18

Maybe best to raise a pull request to update the url. Once the package is updated it will take a few hours to invalid the octolinker cache

**Comment by darkred** [comment]
Just made PR https://github.com/fregante/webext-dynamic-content-scripts/pull/10. 
Thanks for the quick response.

**Comment by darkred** [comment]
> Once the package is updated it will take a few hours to invalid the octolinker cache

@stefanbuck Although my PR was merged immediately (43 hours ago), Octolinker still links to the wronk repo.
Does it take more hours for the Oktolinker cache to become invalidated ?

**Comment by stefanbuck** [comment]
Maybe the cache duration is three days https://github.com/OctoLinker/api/blob/master/src/utils/cache.js#L115 🤦‍♂ I thought I used a much lower value. Sorry about that. I think this is something I wanted to try out anyway, maybe a good time to reduce the caching to 24h.

**Comment by stefanbuck** [comment]
I just updated the cache expire to 12 hours https://github.com/OctoLinker/api/commit/9b8ae0407e8e741181ae6d98f23efa3bd116b86b. However, the cache for this package is still using the previous duration and will be there until his original expire day is reached. Further more OctoLinker is using 4 Redis databases in four different regions so I don't know the exact expire time for you. Let's just wait another 24 hours and we will see if this works.

**Comment by darkred** [comment]
I just checked again, and now it links to the correct repo. 
Thanks for everything!
