### ISSUE TITLE
It adds extra text on this page

### ISSUE THREAD

**Issue by FranklinYu** [OctoLinker/OctoLinker#643]
**Intended outcome:**

```python
from validator import X509Validator, ValidationContext
```

**Actual outcome:**
```python
from validator import X509Validatorvalidator, ValidationContext
```

**How to reproduce the issue:**
Go to https://github.com/alex/x509-validator

Note that I can only reproduce issue on this page. Not sure why it's special.

**Comment by stefanbuck** [comment]
I think this is related to #618. `validator` appears on the left and right side similar to the behaviour described in the link issue. I'll look into this at some point

**Comment by stefanbuck** [comment]
The current version in the Chrome store does not add this extra text.

![image](https://user-images.githubusercontent.com/1393946/72762712-eb9efe00-3be0-11ea-8151-84cc95c05a58.png)

Feel free to reopen the issue again if this still occurs now or later.
