### ISSUE TITLE
Support for Github Actions workflow files

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#649]
The new yaml file format for github actions can reference local files/folders, other repos, and docker containers. The syntax docs are at https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses and you can see a number of examples in the repos at https://github.com/actions and https://github.com/yarnpkg/berry/tree/master/.github/workflows (these link to a number of local files).

**Comment by stefanbuck** [comment]
This is a great idea. Are you interested in contributing this feature? I'm more than happy to help you landing this feature.
