### ISSUE TITLE
Npm dependencies from package.json do not work in Pull requests

### ISSUE THREAD

**Issue by Strajk** [OctoLinker/OctoLinker#71]
npm deps work in file view

![image](https://cloud.githubusercontent.com/assets/697301/15221643/9d64c490-186c-11e6-8b37-12a8694c5fd8.png)

but don't it PR view

![image](https://cloud.githubusercontent.com/assets/697301/15221652/ab48fcde-186c-11e6-94ac-b232c9dd5aba.png)

btw thanks for awesome work

**Comment by stefanbuck** [comment]
Thanks for filling this issue. Unfortunately it's a know issue 😞 I was writing the release notes on an airplane, so I missed to mention it there. I will try to explain why it isn't working in the PR view.

Let's start with the structure of the `package.json` file. Every dependency is declared within a subtree like `dependecies` or `devDependecies`. There are other subtrees like `scripts`, `repository` and many others. To differentiate between them, the extension does a JSON parse on the `blob` so I can use the json representation of this blob to get the dependencies name. 

This approach requires a valid json representation which is never the case in a PR. During develop this feature I spend a couple of weeks and various chat with others to find a better solutions how to identify dependencies in git patch. 

Do you have any idea? If so please let me know.

**Comment by koddsson** [comment]
I'm not super familiar with the internals of octolinker but could we leverage the github api to get the full blob of the file for parsing?

**Comment by josephfrazier** [comment]
That would be a great way to do it, @koddsson! You'd probably want to have [readLines](https://github.com/OctoLinker/browser-extension/blob/64b81952599f12716590ae3ab78643d9fb442c57/packages/blob-reader/helper.js#L129) call [getPath](https://github.com/OctoLinker/browser-extension/blob/64b81952599f12716590ae3ab78643d9fb442c57/packages/blob-reader/helper.js#L27), to find the filename, then use a github API to fetch the full contents.

**Comment by stefanbuck** [comment]
I made some good progress on this today. I'm using the [raw url](https://raw.githubusercontent.com/OctoLinker/OctoLinker/83d3c6793d1f7363ce565b2e970bd9627313e39d/package.json) to fetch the underlying full blob. There is just one issue left. Unchanged lines get not linked on the right hand side just on the left. 

<img width="792" alt="screen shot 2018-07-31 at 00 30 25" src="https://user-images.githubusercontent.com/1393946/43427232-02ef1cb0-9459-11e8-807f-ee7f956a5f35.png">

**Comment by stefanbuck** [comment]
@Strajk it's out 😃
