### ISSUE TITLE
NuGet support for .targets files

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#784]
It's been awhile since I last looked at this code so I wanted to check on this before diving in. Along with the `.csproj` and `.props` file extensions `.targets` can also contain NuGet references. Is this just a matter of adding the extension to the list here? Are there any tests that need to be added/updated?

https://github.com/OctoLinker/OctoLinker/blob/93d85161cd3eacac9ad467dcdd55075a2566a224/packages/plugin-dot-net/index.js#L16

This is an example of a `.targets` file with `PackageReference`s in it.

https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.targets

There's a difference in the format used in these files as well. The `.props` files use `<PackageReference Include=""/>` while `.targets` is using `<PackageReference Update="" />`.

**Comment by xt0rted** [comment]
This was easier than I recalled. Just sent in #785 adding these changes in.

**Comment by stefanbuck** [comment]
I'm glad that it worked out that quick
