### ISSUE TITLE
Support npm Github dependency format

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/OctoLinker#790]
If it's not too much trouble, it would be nice to support [this](https://github.com/tera-proxy/tera-proxy/blob/master/package.json) `github:user/repo` format. Currently it does highlight but the links are not clickable.

**Comment by stefanbuck** [comment]
Should be quite easy to add. I've noticed that GitHub shorthands `user/repo` are broken too so worth fixing them in one go. I'll look into this

**Comment by stefanbuck** [comment]
Fixed and will be part of the upcoming release
