### ISSUE TITLE
Installation from the Microsoft Store keeps throwing CSP errors

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#795]
**Describe the bug**

I just installed OctoLinker on a relatively fresh install of the new Chromium based Edge (*version 79.0.309.71*). I used the link from the readme for the Microsoft Store and the extension installed without error but navigating to this project's `package.json` resulted is nothing being linkified. Looking in the console shows an error of:

```
Refused to connect to 'https://octolinker-api.now.sh/?npm=%40babel%2Fcore%2C%40babel%2Fplugin-proposal-object-rest-spread%2C%40babel%2Fplugin-transform-react-jsx%2C%40babel%2Fplugin-transform-runtime%2C%40babel%2Fpreset-env%2Casync%2Cbabel-core%2Cbabel-eslint%2Cbabel-jest%2Cbabel-loader%2Cbabel-preset-jest%2Cchrome-launch%2Cchrome-webstore-upload-cli%2Ccodecov%2Ccopy-webpack-plugin%2Ccss-loader%2Cdotenv%2Ceslint%2Ceslint-config-airbnb%2Ceslint-config-prettier%2Ceslint-plugin-import%2Ceslint-plugin-jsx-a11y%2Ceslint-plugin-prettier%2Ceslint-plugin-react%2Cjest%2Cjest-fetch-mock%2Cjest-puppeteer%2Cjson%2Cjson-loader%2Clerna%2Cmkdirp%2Cnpm-run-all%2Cprettier%2Cpuppeteer%2Crecursive-readdir%2Csinon%2Cstyle-loader%2Cweb-ext%2Cweb-ext-submit%2Cwebpack%2Cwebpack-cli%2Cwebpack-extension-reloader%2Cfsevents' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com".
```

Refreshing the page results in it sometimes loading and linkifying the file, but most of the time the above error shows in the console. Other files, such as `packages/core/package.json`, don't seem to ever load no matter how many times I go to them or refresh.

If I turn off the Microsoft Store version and install the one from the Chrome Web Store there's no errors in the console and no matter how much I navigate around and refresh the browser it seems to always load and linkify the files.

I tried both with and without a personal access token and the behavior didn't change.

**To Reproduce**

1. Install in Chromium based Edge from the Microsoft Store
2. Browse around the site
3. Most if not all files don't get linkified & CSP errors show in the console
4. Disable the extension and then install from the Chrome Web Store
5. Browse around and things should work

**Expected behavior**

I'd expect the Microsoft Store version to behave just like the Chrome Web Store version.

**Additional context**

**Comment by stefanbuck** [comment]
Seems to be working now with Microsoft Edge: 80.0.361.66

**Comment by xt0rted** [comment]
I'm not seeing the issue anymore either.
