### ISSUE TITLE
Use relativeFile function

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#796]
As discussed in https://github.com/OctoLinker/OctoLinker/pull/789#discussion_r370981882 here's the list of spots that duplicate the `relativeFile` function or something very similar to it.

https://github.com/OctoLinker/OctoLinker/blob/938a9717c106e11f0421bd8607cd0af88893b134/packages/plugin-nodejs-relative-path/index.js#L12-L14

https://github.com/OctoLinker/OctoLinker/blob/938a9717c106e11f0421bd8607cd0af88893b134/packages/plugin-go/index.js#L5-L14

https://github.com/OctoLinker/OctoLinker/blob/938a9717c106e11f0421bd8607cd0af88893b134/packages/plugin-javascript/index.js#L25-L48

https://github.com/OctoLinker/OctoLinker/blob/938a9717c106e11f0421bd8607cd0af88893b134/packages/plugin-ruby/index.js#L8-L16

**Comment by helpsdev** [comment]
Hi there, I'm a first-time contributor, any chance I can work on this?

**Comment by stefanbuck** [comment]
It's already in progress see https://github.com/OctoLinker/OctoLinker/pull/1052 

There are several issues with a "help wanted" label, but not all of them are simple. Maybe one of them is in your own interest and we are more than happy to help.

**Comment by helpsdev** [comment]
Oh I didn't see the #1052 I'll keep looking then. Thank you!

**Comment by stefanbuck** [comment]
@helpsdev there is an outstanding dependency update in our API repo https://github.com/OctoLinker/api/pull/190 I looked into a while ago, but wasn't able to figure out why this breaks the build even I applied all the API changes.  

Edit: Just noticed that there is got@11.7.0 already. Worth updating straight to this version.
