### ISSUE TITLE
`findAndReplaceDOMText cannot handle zero-length matches` on reviews with import/require

### ISSUE THREAD

**Issue by fregante** [OctoLinker/OctoLinker#821]
**Describe the bug**
PR reviews that have review comments with `require`/`import` will fail

**To Reproduce**
1. Go to https://github.com/fregante/pet-names/pull/1/files
4. See error in console

```js
Error: "findAndReplaceDOMText cannot handle zero-length matches"
    prepMatch moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    o moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    search moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    a moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    i moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    r moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:54
    C moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:68
    j moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:68
    j moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:68
    nn moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:225
    <anonymous> moz-extension://61d51579-8113-0c45-9f55-248589474b30/app.js:225
    li https://github.githubassets.com/assets/frameworks-4cbcc25c.js:120
    di https://github.githubassets.com/assets/frameworks-4cbcc25c.js:120
```

**Comment by stefanbuck** [comment]
Thanks for reporting. This party case is quite tricky, but while working on this I've noticed that regular code snippets also broke linking see #829 However, the issue with code suggestion remains, but I'm on it.

**Comment by stefanbuck** [comment]
I'm going to release a first fix for code review comments with code snippets (not to be confused with code suggestion). The raised issue still causes some headache and I wasn't able to find a solution yet. The DOM structure of code suggestions is similar to the blob views DOM which is causes a merge of the both.
