### ISSUE TITLE
OctoLinker seems to cause specific Github pages to freeze in Chrome

### ISSUE THREAD

**Issue by jakeNiemiec** [OctoLinker/OctoLinker#835]
**Describe the bug**
OctoLinker _seems_ to cause specific Github pages to freeze in Chrome. I had to disable my plugins 1 by 1 to find the problem plugin.

**To Reproduce**
1. Go to https://github.com/webpack-contrib/css-loader/issues/1050 with the plugin enabled
2. Find that you cannot right click etc. Open the **Chrome** task manager and end the process.

**Additional context**
- The background page for the plugin did not have any errors or other indication that there was a problem.  
- Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- This is the **only** page where I can reliably produce this bug. 
- The freeze will not happen if you are not logged in.

**Comment by jakeNiemiec** [comment]
Relaunching Chrome updated me to version 80.0.3987.1**32**, the problem seems to be resolved. I am not sure if it was on the Chrome or Github side.

**Comment by stefanbuck** [comment]
Ohh, let's hope for the best. Please feel free to reopen this issue anytime
