### ISSUE TITLE
Support Cargo.toml

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/OctoLinker#857]
**Describe the feature**
Support linking Rust crates defined in `Cargo.toml`.

**Demo**
- https://github.com/actix/examples/blob/5320117bcaeb8391dbf313bf897d978b2e588295/basics/Cargo.toml#L10 should resolve to https://github.com/actix/actix-web
- https://github.com/actix/examples/blob/5320117bcaeb8391dbf313bf897d978b2e588295/basics/Cargo.toml#L17 should resolve to https://github.com/tokio-rs/bytes

**Additional information**
Crate resolution already works in [`.rs` files](https://github.com/actix/examples/blob/master/basics/src/main.rs).

**Comment by stefanbuck** [comment]
Will be part of the next release (most likely next week)

**Comment by silverwind** [comment]
Nice work @xt0rted!
