### ISSUE TITLE
New permission https://api.github.com

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/OctoLinker#870]
Hello,

our next version of OctoLinker v6.3 will ask for one additional site permission to get read and change access to https://api.github.com!

This change **will temporarily disable OctoLinker** and you have to agree to the new permission to re-enable OctoLinker.

![](https://user-images.githubusercontent.com/1393946/78512363-25c17a00-77a4-11ea-896c-b11db6d15fe5.png)

### Why the change?

We want to be clear about permissions OctoLinker is using. Furthermore we need to ensure OctoLinker stays compliant with Google's [Web Store Policy](https://developer.chrome.com/webstore/terms). Also this change allows us to simplify our build process a little.

It's important to note, that **OctoLinker is accessing https://api.github.com already**, to fetch a file tree of the repository to make relative file lookup work, so basically nothing will change. 

If you have configured a GitHub token, OctoLinker will make requests on your behalf and we recommend you use a GitHub token to extend the rate limit for authenticated requests and enable private repository support.

This change will be part of our next release v6.3 which is planned for April 13, 2020, but we wanted to inform you well ahead of the change.

What if I have questions or concerns? We're here to help! Please leave a comment below or contact us on Twitter @octolinker.

OctoLinker Team

**Comment by stefanbuck** [comment]
Another release with a permission request is needed, because I add `api.github.com` to the wrong mainfest field 🤦

**Comment by Chaz6** [comment]
What is the requirement for the "change" permission on api.github.com? I couldn't find it in your description. I would not expect this extension to need to change anything.

**Comment by stefanbuck** [comment]
Unfortunately there is no option to define fine grained permissions in a browser extensions. `read` access goes along with `change` permission which I agree can be confusing. OctoLinker needs to be able to access api.github.com to perform a GET request as describe above. No other requests are made. I hope this was helpful und please let me know if you have any concern
