### ISSUE TITLE
Haskell not working

### ISSUE THREAD

**Issue by adamsmd** [OctoLinker/OctoLinker#892]
**Describe the bug**
OctoLinker doesn't seem to be working on Haskell files.

**To Reproduce**
1. Go to https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Main.hs
2. Scroll down to the 'import' statements

**Expected behavior**
The import statements should become links.

**Actual behavior**
The import statements are not links.

**Other potentially useful information**
I'm using OctoLinker 6.3.0 from addons.mozzila.org and Firefox 75.0 on Ubuntu 19.10.

Note that OctoLinker is working for Java files (e.g., https://github.com/remkop/picocli/blob/master/src/main/java/picocli/AutoComplete.java), so I suspect it is something specific to Haskell or OctoLinker's plugin for Haskell.

I am using OctoLinker as it comes "out-of-the-box" with a personal access token but no other configuration. Is there some configuration I need to do for Haskell to work?

Note that in https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Main.hs the lines starting with 'import Idris' are importing files local to the project.  But the lines starting with 'import Control', 'import Data' and 'import System' are external library imports.

**Comment by xt0rted** [comment]
@stefanbuck this is an odd one. In Chrome this file loads fine, but in FireFox it throws a network error on https://github.com/OctoLinker/OctoLinker/blob/e408d7000d0758194c7dc6888cb1c4dfc02267db/packages/helper-github-api/fetch-tree.js#L17-L23

I can run that exact code in dev tools and it resolves as expected, but inside the extension it throws.

```
TypeError: "NetworkError when attempting to fetch resource."
    default fetch-tree.js:17
    default loader.js:138
    run app.js:53
```

I get that error on every `.hs` file I load in FireFox. I'm also seeing it when I view other file types with local references such as https://github.com/OctoLinker/OctoLinker/blob/e408d7000d0758194c7dc6888cb1c4dfc02267db/packages/core/app.js#L7-L11 and https://github.com/OctoLinker/OctoLinker/blob/e408d7000d0758194c7dc6888cb1c4dfc02267db/e2e/fixtures/dotnet/sdk/Project.csproj#L33-L63

**Comment by stefanbuck** [comment]
Thanks both. I looked into it and it turned out it was my fault with the recent permission update #894. I'll release a new version asap
