### ISSUE TITLE
Add dark color scheme support in the options

### ISSUE THREAD

**Issue by fregante** [OctoLinker/OctoLinker#893]
_You can save 130KB or more if you switch to [webext-base-css](https://github.com/fregante/webext-base-css) today!_

`options.js` goes from 160KB to 30KB if you drop Primer. This would also add support for Dark color scheme and integrate with the browser’s style.

This is what it looks like with only `webext-base-css` (you'll need a couple of extra rules to fix the sizing and margins, or drop DT/DD)

<img width="674" alt="" src="https://user-images.githubusercontent.com/1402241/79556647-aa17d500-80a1-11ea-87ce-9b4f12c0c880.png">
<img width="395" alt="" src="https://user-images.githubusercontent.com/1402241/79556649-aab06b80-80a1-11ea-9a56-4e2f697e11ff.png">

**Comment by stefanbuck** [comment]
I'm not a dark mode user myself, but whoever is interested in this change is welcome to submit a Pull Request.

**Comment by fregante** [comment]
Would that interfere with the usage on your site? I think I saw some references to it in the code

**Comment by stefanbuck** [comment]
I didn't get it, sorry. Can you explain in more detail?

**Comment by fregante** [comment]
I saw this:
https://github.com/OctoLinker/OctoLinker/blob/8eeb5ba93da277d46b30384a9d46043afe19f02f/packages/helper-settings/index.js#L11-L19

I thought that the options page was somehow being also shown on the live demo site.

**Comment by fregante** [comment]
Working on it

**Comment by stefanbuck** [comment]
No, the options page is not shown on the live demo site. This early return is needed to bypass the settings call which is made during the initialisation phase.
