### ISSUE TITLE
Request: A less intrusive alternative to the announcement banner.

### ISSUE THREAD

**Issue by dylang** [OctoLinker/OctoLinker#918]
**Describe the feature**

I love this plugin and really appreciate the time and work put into it by the creator and contributors.

It's also exciting to know about new features.

But the banners are too much in my opinion. 

Especially when using multiple browsers, Github and Github Enterprise. So many instances of the banner and places to dismiss them I personally don't even read them anymore. Instead, they annoying distractions that I need to manually dismiss.

**Demo**

How about using the UI that OctoLinker generates? Put the messaging in the product, where we'll see it when we use it.

<img width="788" alt="Screen Shot 2020-05-01 at 3 32 14 PM" src="https://user-images.githubusercontent.com/51505/80835668-39080f80-8bc1-11ea-99b3-2c5f5fc49715.png">

This way it is relevant to what the user is doing, using Octolinker, instead of forcing it just because the user happens to have come back to Github for some reason.

That's just one idea.

**Additional information**

Look at all the browser plugins we have installed.... What if they all started inserting announcement banners on each update? My guess is that, for most of us, it would not be pleasant.

Thanks for considering this idea, and thank you again for the great tool.

**Comment by stefanbuck** [comment]
Thanks for your feedback. We haven't heard any negative feedback so far, but I get your point. Did you know, that there is an option in the extensions settings dialog to disable this notification? Maybe this options needs to be promoted through a banner ... just kidding. I'll keep this issue open to collect feedback and will also consider your suggestion. Thanks for sharing your thoughts with us. 

![Screenshot 2020-05-01 at 23 08 36](https://user-images.githubusercontent.com/1393946/80841949-be5ee480-8c00-11ea-91c7-98177588a95a.png)

**Comment by dylang** [comment]
> there is an option in the extensions settings dialog to disable this notification

I did not, thank you for sharing!

> Maybe this options needs to be promoted through a banner ... just kidding. 

Haha, I appreciate the humor!

**Comment by RyanCopley** [comment]
FWIW, I also thought the banner was also really obnoxious. I have been dealing with annoying misclicks because of it for months now, only just now realizing that  it was because of a 3rd party app I installed and forgot about (facepalm!)... but I do appreciate that there is a setting. However, the current implementation is really obnoxious because its height is not fixed. As the page loads, it causes content to shift around, causing me to misclick way too often. It may be worth simply trying to address that as it would have caused less headaches for users.

**Comment by stefanbuck** [comment]
Thanks for sharing your thoughts with us @RyanCopley. I can imagine how annoying such misclicks are so we will address it and come up with a solution for it. Just for clarification, you said your are dealing with this issue for months, but the banner is only show on major and minor releases. The last minor release was on April 30th. Is the banner popping up on a regular basis even there is no new release?

**Comment by stefanbuck** [comment]
Hi @dylang  @RyanCopley, I opened a new issue to discuss this request in detail https://github.com/OctoLinker/OctoLinker/issues/973. Please feel free to add your thoughts. Thank you

**Comment by stefanbuck** [comment]
First attempt of a new notification design / system https://github.com/OctoLinker/OctoLinker/pull/975
