### ISSUE TITLE
Links aren't inserted when using extensions to show whitespace

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/OctoLinker#942]
Extensions such as [Refined GitHub](https://github.com/sindresorhus/refined-github) and [Render Whitespace on GitHub](https://github.com/glebm/render-whitespace-on-github) replaces whitespace with `<span>` inside of dependency names/paths. Because of this Octolinker doesn't match the text and insert a link for them.

ref: https://github.com/OctoLinker/OctoLinker/pull/836#issuecomment-631359175

**Comment by TehShrike** [comment]
This must be what broke Octolinker for me recently.  Links haven't been showing up for me since I set up this new machine.  Maybe in this new setup, Refined Github is getting to modify the DOM before Octolinker gets to it?

It's really messing up my workflow, I leaned on Octolinker pretty heavily to navigate repositories 😅

**Comment by stefanbuck** [comment]
Sorry for getting you hooked 😄

Are all links broken or just paths containing a whitespace as mentioned in https://github.com/OctoLinker/OctoLinker/pull/836#issuecomment-631359175?

**Comment by TehShrike** [comment]
All links, across all public or private projects since I set up this new computer.  (More context: I basically only browse JS files)

**Comment by stefanbuck** [comment]
Mhhh, I use Refined GitHub as well and it's working fine for me. Can you confirm that disabling Refined GitHub and any other GitHub related extension will fix it? Which browser are you using?

**Comment by TehShrike** [comment]
welp, I tried disabling all extensions except for OctoLinker, and the issue persists :-x

I'm on Firefox 94.

**Comment by xt0rted** [comment]
The issue @TehShrike is having is a bug in Firefox. See #1414 for two says to fix this.

**Comment by stefanbuck** [comment]
@TehShrike it took a while, but a fixed has just been published to the Mozilla store. Watch out for v6.10.1
