### ISSUE TITLE
OctoLinker notifications 

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/OctoLinker#973]
Over the past few months I received a few complains about the notifications that OctoLinker adds to GitHub. This issue is about discussing the future of such notifications. There are two type of notifications:

- Extension update: A short teaser with a link to our release notes
- GitHub API: For private repos and to increase the hourly rate limit, OctoLinker is asking to provide a GitHub token. This token is exclusively  used to fetch a tree structure of the repository in order to provide linking for relative files. 

The first one, can be dropped easily, although it provides value and I did recivied feedback that people also like it. Maybe it just needs a different styling to avoid jumping of the page as described in https://github.com/OctoLinker/OctoLinker/issues/918#issuecomment-651914827.

The latter is slightly more tricky, since it contains instructions how to enable support for private repositories. Without such a hint it's very likely that users think OctoLinker is broken.

## What can we do to solve this? 

A few quick thoughts from my side. Please feel free to comment and add your ideas.

a) After installing, open the settings dialog which makes people aware of the token / private repo feature.
b) Perhaps we could explain, through popup the purpose of a token when installing OctoLinker for the first time. 
c) Redirect to a getting started page with further instructions
d) Put a messaging next to a link in case this can't be resolved due to the missing GitHub token. 

# Screenshots

### Extension update 
<img width="1228" alt="Screenshot 2020-07-12 at 23 36 09" src="https://user-images.githubusercontent.com/1393946/87257138-901b4200-c498-11ea-848d-7580d482a423.png">

### Private repo
<img width="1222" alt="Screenshot 2020-07-12 at 23 33 38" src="https://user-images.githubusercontent.com/1393946/87257142-94dff600-c498-11ea-9b69-db0ed3555236.png">

### Rate limit
<img width="1229" alt="Screenshot 2020-07-12 at 23 34 42" src="https://user-images.githubusercontent.com/1393946/87257139-914c6f00-c498-11ea-9b68-fae4ba83291f.png">

**Comment by RyanCopley** [comment]
I officially received an update to OctoLinker and the new experience is :100: ! ! Thank you

**Comment by stefanbuck** [comment]
Glad to hear
